import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { useMutation } from "@tanstack/react-query";
import { RefreshCw, Send } from "lucide-react";
import { useMemo, useRef, useState } from "react";

interface MockYouTubePost {
  id: string;
  title: string;
  description: string;
  hashtags: string[];
}

interface YouTubePostResponse {
  success: boolean;
  postId: string;
  watchUrl?: string;
  studioUrl?: string;
  message?: string;
  usedSampleVideo?: boolean;
}

interface YouTubePostPayload {
  title: string;
  description: string;
  video?: File | null;
}

const ytHooks = [
  "New walkthrough:",
  "Neighborhood tour:",
  "Listing spotlight:",
  "Behind the scenes:",
  "Market update:",
];

const ytHashSets = [
  ["#YouTubeShorts", "#OmahaRealEstate", "#MikeBjork"],
  ["#HomeTour", "#NebraskaHomes", "#RealEstate"],
  ["#HouseHunting", "#DreamHome", "#RealtorLife"],
];

function buildRandomYouTubePost(seed: number): MockYouTubePost {
  const randomFrom = <T,>(arr: T[]): T =>
    arr[Math.floor(Math.random() * arr.length)];

  const hook = randomFrom(ytHooks);
  const price = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(425000 + (seed % 6) * 25000);

  const title = `${hook} ${price}`;
  const hashtags = randomFrom(ytHashSets);

  const description = [
    `${hook} Stunning home at ${price}.`,
    "",
    "Quick test video generated by RealtyFlow.",
    hashtags.join(" "),
  ].join("\n");

  return {
    id: `yt-mock-${seed}`,
    title,
    description,
    hashtags,
  };
}

export function YouTubeTestPosts() {
  const { toast } = useToast();
  const [seed, setSeed] = useState(() => Math.floor(Math.random() * 1000));
  const [selectedVideo, setSelectedVideo] = useState<File | null>(null);
  const [lastUpload, setLastUpload] = useState<{
    title: string;
    watchUrl?: string;
    studioUrl?: string;
  } | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const posts = useMemo(() => {
    return Array.from({ length: 3 }, (_, index) =>
      buildRandomYouTubePost(seed + index)
    );
  }, [seed]);

  const handleVideoChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    setSelectedVideo(file || null);
  };

  const clearSelectedVideo = () => {
    setSelectedVideo(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const postMutation = useMutation({
    mutationFn: async (post: YouTubePostPayload) => {
      const formData = new FormData();
      formData.append("title", post.title);
      formData.append("description", post.description);

      if (post.video) {
        formData.append("video", post.video);
      }

      const response = await fetch("/api/youtube/post", {
        method: "POST",
        body: formData,
        credentials: "include",
      });

      const data = await response.json().catch(() => ({}));

      if (!response.ok) {
        throw new Error(data.error || "Failed to post to YouTube");
      }

      return data as YouTubePostResponse;
    },
    onSuccess: (data, variables) => {
      setLastUpload({
        title: variables.title,
        watchUrl: data.watchUrl,
        studioUrl: data.studioUrl,
      });
      toast({
        title: "YouTube test sent",
        description: data.watchUrl
          ? "Video uploaded. Tap to view on YouTube."
          : data.message || "Posted mock content to YouTube.",
      });
    },
    onError: (error: any) => {
      toast({
        title: "YouTube post failed",
        description: error.message || "Unable to post mock content.",
        variant: "destructive",
      });
    },
  });

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0">
        <div>
          <CardTitle className="text-lg">YouTube Quick Test Posts</CardTitle>
          <p className="text-sm text-muted-foreground">
            Use these ready-to-send samples to verify the YouTube integration.
          </p>
        </div>
        <Button
          variant="ghost"
          size="icon"
          onClick={() => setSeed(Math.floor(Math.random() * 1000))}
          aria-label="Refresh mock posts"
        >
          <RefreshCw className="h-4 w-4" />
        </Button>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="rounded-md border border-dashed border-border bg-muted/30 p-4 space-y-2">
          <p className="text-sm text-muted-foreground">
            Optional: upload a video file to send to YouTube. Leave this empty
            to use the built-in RealtyFlow sample clip.
          </p>
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
            <Input
              ref={fileInputRef}
              type="file"
              accept="video/*"
              onChange={handleVideoChange}
              disabled={postMutation.isPending}
            />
            {selectedVideo && (
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={clearSelectedVideo}
                disabled={postMutation.isPending}
              >
                Clear file
              </Button>
            )}
          </div>
          {selectedVideo && (
            <p className="text-xs text-muted-foreground">
              Selected: {selectedVideo.name} (
              {(selectedVideo.size / (1024 * 1024)).toFixed(2)} MB)
            </p>
          )}
        </div>
        {posts.map((post) => (
          <div
            key={post.id}
            className="rounded-md border border-dashed border-border bg-muted/30 p-4 space-y-3"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Badge variant="secondary">Mock</Badge>
                <span className="font-medium text-foreground">
                  {post.title}
                </span>
              </div>
              <Button
                size="sm"
                onClick={() =>
                  postMutation.mutate({
                    title: post.title,
                    description: post.description,
                    video: selectedVideo,
                  })
                }
                disabled={postMutation.isPending}
              >
                <Send className="mr-2 h-4 w-4" />
                {postMutation.isPending ? "Posting..." : "Post to YouTube"}
              </Button>
            </div>
            <Textarea
              value={post.description}
              readOnly
              className="min-h-[140px] text-sm"
            />
          </div>
        ))}
        {lastUpload && (
          <div className="rounded-md border border-border bg-muted/50 p-4 text-sm">
            <p className="font-medium">
              Last upload:{" "}
              <span className="font-semibold">{lastUpload.title}</span>
            </p>
            <div className="mt-2 flex flex-wrap gap-4">
              {lastUpload.watchUrl && (
                <a
                  href={lastUpload.watchUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="text-primary underline"
                >
                  Watch on YouTube
                </a>
              )}
              {lastUpload.studioUrl && (
                <a
                  href={lastUpload.studioUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="text-primary underline"
                >
                  Open in Studio
                </a>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
