CREATE TABLE IF NOT EXISTS social_api_keys (
  id VARCHAR PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id VARCHAR NOT NULL,
  facebook_app_id TEXT,
  facebook_app_secret TEXT,
  instagram_token TEXT,
  instagram_business_account_id TEXT,
  tiktok_api_key TEXT,
  tiktok_api_secret TEXT,
  tiktok_access_token TEXT,
  twitter_api_key TEXT,
  twitter_api_secret TEXT,
  twitter_access_token TEXT,
  twitter_access_token_secret TEXT,
  twitter_bearer_token TEXT,
  youtube_api_key TEXT,
  youtube_channel_id TEXT,
  linkedin_access_token TEXT,
  linkedin_organization_id TEXT,
  keys_configured BOOLEAN DEFAULT false,
  last_updated TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW()
);
