import { Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface AiGeneratedBadgeProps {
  size?: "sm" | "md" | "lg";
  showTooltip?: boolean;
  variant?: "default" | "outline" | "secondary";
  className?: string;
}

export function AiGeneratedBadge({
  size = "sm",
  showTooltip = true,
  variant = "outline",
  className = "",
}: AiGeneratedBadgeProps) {
  const sizeClasses = {
    sm: "text-xs px-1.5 py-0.5",
    md: "text-sm px-2 py-1",
    lg: "text-base px-3 py-1.5",
  };

  const iconSizes = {
    sm: "h-3 w-3",
    md: "h-4 w-4",
    lg: "h-5 w-5",
  };

  const badge = (
    <Badge
      variant={variant}
      className={`${sizeClasses[size]} ${className} border-purple-500/50 text-purple-700 dark:text-purple-400 bg-purple-50 dark:bg-purple-950/30`}
      data-testid="badge-ai-generated"
      aria-label="Content generated by AI"
    >
      <Sparkles className={`${iconSizes[size]} mr-1`} />
      AI Generated
    </Badge>
  );

  if (showTooltip) {
    return (
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>{badge}</TooltipTrigger>
          <TooltipContent>
            <p className="text-xs">This content was generated using AI</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    );
  }

  return badge;
}
